# Change baseurl before deploy
baseurl = "http://www.dizs.site"
languageCode = "zh-cn"
title = "AI.3407"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    ID = 'G-26P4NX9J8P'

  [services.umami_analytics]
    id = '43d3a0eb-c178-4a45-932d-f2a107809b24'
    script_url = 'https://cloud.umami.is/script.js'